### ISSUE TITLE
Running the program

### ISSUE THREAD

**Issue by jachermocilla** [palaparearl/specialproblem#1]
Hi earl, 

When I run the jar file I can only access the main menu. Are there dependencies that need to be installed?

Thanks!

**Comment by palaparearl** [comment]
Hi Sir Jach,

The jar file that you have run is an outdated version, from a repository
that contains all of my drafts. Would I need to send you the final jar file
of the application?

Thank you, sir!

**Comment by jachermocilla** [comment]
Yes please. We'll try to use it in 125 for next week's lab on shell scripting. Thanks.

**Comment by palaparearl** [comment]
Sir, would it be possible for me to send it next week or the week after
that? I'm currently in a quarantine facility with no access to my computer,
and I still have no idea when I will be cleared to leave. Hoping for your
kind consideration. Thank you, sir!

**Comment by jachermocilla** [comment]
Sure. Take care over there.

**Comment by palaparearl** [comment]
Thank you, sir

**Comment by palaparearl** [comment]
Hi Sir Jach,

I have just updated the GitHub repository with the final version of the jar
file of the application. Thank you, sir!

**Comment by jachermocilla** [comment]
Thanks earl! It's great that you are well now.

**Comment by palaparearl** [comment]
You're welcome sir. I'm still recovering as of now though. Thank you for
the concern, sir.
